name: plannotate
channels:
  - conda-forge
  - bioconda
dependencies:
  - blast>=2.10.1
  - curl
  - diamond>=2.0.13
  - infernal>=1.1.4
  - pip
  - python>=3.10
  - trnascan-se>=2.0.7
  - pip:
      - -e .[test]
