name: plannotate
channels:
  - conda-forge
  - bioconda
dependencies:
  - blast=2.17.0
  - curl
  - diamond=2.1.24
  - infernal=1.1.5
  - pip
  - python>=3.10
  - trnascan-se>=2.0.7
  - pip:
      - -e .[test]
