[tool.poetry]
name = "plannotate"
version = "0.1.0"
description = ""
authors = ["Alex Naka <alexn@science.xyz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
biopython = "^1.81"
click = "7.1.2"
numpy = "^1.24.3"
pandas = "^2.0.2"
streamlit = "1.8.1"
tabulate = "^0.9.0"
altair = "4.2.2"
protobuf = "3.20"
biotite = "^0.37.0"
tqdm = "^4.65.0"
bokeh = "^3.1.1"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.23.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
