#!/usr/bin/env python3

"""
FPbase Blurb Generator

A self-contained Python script to generate protein blurbs from FPbase GraphQL API data.
Based on the logic from backend/proteins/util/blurb.py and related utility functions.

This was largely generated by Claude Code, inspecting the fpbase git repo. I had to do
this because the GraphQL API does not provide the blurb data directly. This extracts
that logic and applies it to the data fetched from the API.

Usage:
    python3 gather_fpbase.py [OPTIONS]

Options:
    -o, --output FILE       Output TSV file (default: stdout)
    --fasta FILE           Output FASTA file for sequences
    -l, --limit N          Limit to first N proteins (default: all)
    --with-bright          Include brightness comparison in blurbs
    --save-json FILE       Save raw JSON data to file
    -v, --verbose          Enable verbose logging
    -h, --help             Show this help message

Output Format:
    TSV: name, slug, blurb
    FASTA: >slug\nsequence

Examples:
    python3 gather_fpbase.py                           # Output TSV to stdout
    python3 gather_fpbase.py -o proteins.tsv          # Save TSV to file
    python3 gather_fpbase.py --fasta proteins.fasta   # Save sequences to FASTA
    python3 gather_fpbase.py -o proteins.tsv --fasta proteins.fasta  # Both outputs
    python3 gather_fpbase.py -l 100 --with-bright     # First 100 proteins with brightness
"""

import argparse
import csv
import json
import logging
import sys
from typing import Any, Dict, List, Optional

import requests


def get_color_group(ex_max: Optional[float], em_max: Optional[float]) -> str:
    """
    Determine color group based on excitation and emission maxima.
    Based on backend/proteins/util/helpers.py get_color_group function.
    """
    if not ex_max or not em_max:
        return ""

    if (em_max - ex_max) > 90:
        return "Long Stokes Shift"
    if ex_max < 380:
        return "UV"
    if ex_max < 421:
        return "Blue"
    if ex_max < 473:
        return "Cyan"
    if ex_max < 505:
        return "Green"
    if ex_max < 515:
        return "Green/Yellow"
    if ex_max < 531:
        return "Yellow"
    if ex_max < 555:
        return "Orange"
    if ex_max < 600:
        return "Red"
    if ex_max < 631:
        return "Far Red"
    if ex_max < 800:
        return "Near IR"
    return ""


def get_switch_type_display(switch_type: Optional[str]) -> str:
    """Convert switch type code to display string."""
    if not switch_type:
        return "basic"

    switch_types = {
        "B": "basic",
        "PA": "photoactivatable",
        "PS": "photoswitchable",
        "PC": "photoconvertible",
        "MP": "multi-photochromic",
        "T": "timer",
        "O": "multistate",
    }
    return switch_types.get(switch_type.upper(), "basic")


def get_agg_display(agg: Optional[str]) -> str:
    """Convert aggregation code to display string."""
    if not agg:
        return ""

    agg_types = {
        "M": "monomer",
        "D": "dimer",
        "TD": "tandem dimer",
        "WD": "weak dimer",
        "T": "tetramer",
    }
    return agg_types.get(agg.upper(), "")


def get_cofactor_display(cofactor: Optional[str]) -> str:
    """Convert cofactor code to display string."""
    if not cofactor:
        return ""

    cofactor_types = {
        "BR": "bilirubin",
        "BV": "biliverdin",
        "FL": "flavin",
        "PC": "phycocyanobilin",
        "RL": "ribityl-lumazine",
    }
    return cofactor_types.get(cofactor.upper(), "")


def calculate_local_brightness(
    protein: Dict[str, Any], all_proteins: List[Dict[str, Any]]
) -> float:
    """
    Calculate local brightness relative to spectral neighbors.
    Simplified version of the local_brightness property logic.
    """
    if not protein.get("defaultState") or not protein["defaultState"].get("brightness"):
        return 1.0

    current_brightness = protein["defaultState"]["brightness"]
    current_em = protein["defaultState"].get("emMax")

    if not current_em:
        return 1.0

    # Find proteins with similar emission (within 20nm)
    similar_proteins = []
    for other_protein in all_proteins:
        if (
            other_protein.get("defaultState")
            and other_protein["defaultState"].get("emMax")
            and other_protein["defaultState"].get("brightness")
            and other_protein["id"] != protein["id"]
        ):
            other_em = other_protein["defaultState"]["emMax"]
            if abs(other_em - current_em) <= 20:
                similar_proteins.append(other_protein["defaultState"]["brightness"])

    if not similar_proteins:
        return 1.0

    # Calculate average brightness of similar proteins
    avg_brightness = sum(similar_proteins) / len(similar_proteins)

    # Return ratio (local brightness)
    return current_brightness / avg_brightness if avg_brightness > 0 else 1.0


def generate_blurb(
    protein: Dict[str, Any],
    all_proteins: List[Dict[str, Any]],
    with_bright: bool = False,
    with_bleach: bool = False,
) -> str:
    """
    Generate protein blurb from API data.
    Based on backend/proteins/util/blurb.py long_blurb function (default website behavior).
    """
    name = protein.get("name", "")
    blurb = name

    # Get switch type
    switch_type = protein.get("switchType")
    switch = get_switch_type_display(switch_type)
    if switch == "basic":
        switch += " (constitutively fluorescent)"

    # Get color
    default_state = protein.get("defaultState")
    color = ""
    if default_state:
        ex_max = default_state.get("exMax")
        em_max = default_state.get("emMax")
        color = get_color_group(ex_max, em_max)

    # Build basic description
    vowel_prefix = "n" if switch.startswith(("a", "e", "i", "o", "u")) else ""
    switch_part = f" {switch}" if switch else ""
    color_part = f" {color.lower()}" if color else ""

    blurb += f" is a{vowel_prefix}{switch_part}{color_part} fluorescent protein"

    # Add publication year
    primary_ref = protein.get("primaryReference")
    if primary_ref and primary_ref.get("year"):
        blurb += f" published in {primary_ref['year']}"
        # Add DOI if available
        if primary_ref.get("doi"):
            blurb += f" (DOI: {primary_ref['doi']})"

    # Add organism
    parent_org = protein.get("parentOrganism")
    if parent_org and parent_org.get("scientificName"):
        blurb += f", derived from {parent_org['scientificName']}. "
    else:
        blurb += ". "

    # Add brightness information if available (matching template logic)
    if default_state:
        bright = None
        # Template always includes brightness if brightness data exists
        if with_bright and default_state.get("brightness"):
            local_brightness = calculate_local_brightness(protein, all_proteins)
            if local_brightness > 1.5:
                bright = "much brighter than"
            elif local_brightness > 1.1:
                bright = "slightly brighter than"
            elif local_brightness > 0.9:
                bright = "of average brightness compared to"
            elif local_brightness > 0.5:
                bright = "slightly dimmer than"
            elif local_brightness <= 0.5:
                bright = "much dimmer than"

        if bright:
            blurb += f"It is {bright} other proteins in the database with similar emission spectra. "

        # Add maturation information (matching template thresholds)
        mature = None
        maturation = default_state.get("maturation")
        if maturation:
            if maturation <= 15:
                mature = "very rapidly-maturing"
            elif maturation < 45:
                mature = "rapidly-maturing"
            elif maturation < 70:
                mature = "somewhat slowly-maturing"
            elif maturation < 100:
                mature = "slowly-maturing"
            elif maturation >= 100:
                mature = "very slowly-maturing"

        if mature:
            agg_display = get_agg_display(protein.get("agg"))
            protein_type = agg_display if agg_display else "protein"
            blurb += f"It is reported to be a {mature} {protein_type}"

        # Add acid sensitivity
        acid = None
        pka = default_state.get("pka")
        if pka:
            if pka > 6:
                acid = "high"
            elif pka > 5:
                acid = "moderate"
            elif pka >= 4:
                acid = "low"
            elif pka < 4:
                acid = "very low"

        if acid:
            if mature:
                blurb += " with "
            else:
                blurb += "It has "
            blurb += f"{acid} acid sensitivity."
        elif mature and not pka:
            blurb += "."
    else:
        # No default state, add aggregation info if available
        agg_display = get_agg_display(protein.get("agg"))
        if agg_display:
            blurb += f"It is reported to be a {agg_display}."

    # Add cofactor information
    cofactor = protein.get("cofactor")
    if cofactor:
        cofactor_display = get_cofactor_display(cofactor)
        if cofactor_display:
            blurb += f" It requires the cofactor {cofactor_display} for fluorescence."

    return blurb.strip()


def fetch_fpbase_data(
    url: str = "https://www.fpbase.org/graphql/",
) -> List[Dict[str, Any]]:
    """Fetch protein data from FPbase GraphQL API."""
    query = """
    { 
      proteins { 
        id 
        name 
        slug
        seq
        switchType 
        agg 
        cofactor 
        parentOrganism { 
          scientificName 
        } 
        primaryReference { 
          year 
          doi
        } 
        defaultState { 
          maturation 
          pka 
          extCoeff 
          qy 
          brightness 
          exMax 
          emMax 
        } 
        states { 
          name
          maturation 
          pka 
          extCoeff 
          qy 
          brightness 
          exMax 
          emMax 
        } 
      } 
    }
    """

    response = requests.post(url, json={"query": query})
    response.raise_for_status()

    data = response.json()
    if "errors" in data:
        raise Exception(f"GraphQL errors: {data['errors']}")

    return data["data"]["proteins"]


def filter_valid_proteins(
    proteins: List[Dict[str, Any]], limit: Optional[int] = None
) -> List[Dict[str, Any]]:
    """Filter proteins with valid names and sequences."""
    logger = logging.getLogger(__name__)

    valid_proteins = []
    skipped_no_name = 0
    skipped_no_seq = 0

    for protein in proteins:
        name = protein.get("name", "")
        seq = protein.get("seq", "")

        if not name:
            skipped_no_name += 1
            continue

        if not seq:
            skipped_no_seq += 1
            logger.debug(f"Skipping protein '{name}' - no sequence data")
            continue

        valid_proteins.append(protein)

    # Log filtering results
    logger.info(
        f"Filtered proteins: {len(valid_proteins)} valid, {skipped_no_name} without names, {skipped_no_seq} without sequences"
    )

    # Limit proteins if specified
    if limit:
        valid_proteins = valid_proteins[:limit]
        logger.debug(f"Limited to first {limit} proteins")

    return valid_proteins


def write_tsv_output(
    proteins: List[Dict[str, Any]],
    output_file,
    limit: Optional[int] = None,
    with_bright: bool = False,
):
    """Write protein data to TSV format (without sequences)."""
    writer = csv.writer(output_file, delimiter="\t")

    # No header for TSV output

    # Filter valid proteins
    valid_proteins = filter_valid_proteins(proteins, limit)

    # Write data rows
    for protein in valid_proteins:
        name = protein.get("name", "")
        slug = protein.get("slug", "")
        # Use original full protein list for brightness comparison, not filtered list
        blurb = generate_blurb(
            protein, proteins, with_bright=with_bright, with_bleach=False
        )

        writer.writerow([name, slug, blurb])


def write_fasta_output(
    proteins: List[Dict[str, Any]],
    output_file,
    limit: Optional[int] = None,
):
    """Write protein sequences to FASTA format using slug as header.

    Creates a FASTA file with protein sequences where each sequence uses the
    protein's slug as the FASTA header (fallback to name if slug unavailable).
    Only includes proteins with valid sequences.
    """

    # Filter valid proteins
    valid_proteins = filter_valid_proteins(proteins, limit)

    # Write FASTA sequences
    for protein in valid_proteins:
        slug = protein.get("slug", "")
        seq = protein.get("seq", "")
        name = protein.get("name", "")

        # Use slug as header, fallback to name if no slug
        header = slug if slug else name
        if header:
            output_file.write(f">{header}\n{seq}\n")


def main():
    """Main CLI function."""
    parser = argparse.ArgumentParser(
        description="Generate protein blurbs from FPbase GraphQL API data",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 gather_fpbase.py                           # Output TSV to stdout
  python3 gather_fpbase.py -o proteins.tsv           # Save TSV to file
  python3 gather_fpbase.py --fasta proteins.fasta    # Save sequences to FASTA
  python3 gather_fpbase.py -o proteins.tsv --fasta proteins.fasta  # Both TSV and FASTA
  python3 gather_fpbase.py -l 100 --with-bright      # First 100 proteins with brightness
        """,
    )

    parser.add_argument(
        "-o", "--output", type=str, help="Output TSV file (default: stdout)"
    )

    parser.add_argument("--fasta", type=str, help="Output FASTA file for sequences")

    parser.add_argument(
        "-l", "--limit", type=int, help="Limit to first N proteins (default: all)"
    )

    parser.add_argument(
        "--with-bright",
        action="store_true",
        help="Include brightness comparison in blurbs",
    )

    parser.add_argument("--save-json", type=str, help="Save raw JSON data to file")

    parser.add_argument(
        "-v", "--verbose", action="store_true", help="Enable verbose logging"
    )

    args = parser.parse_args()

    # Setup logging
    log_level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(
        level=log_level,
        format="%(asctime)s - %(levelname)s - %(message)s",
        handlers=[logging.StreamHandler(sys.stderr)],
    )
    logger = logging.getLogger(__name__)

    try:
        # Fetch data
        logger.info("Fetching protein data from FPbase API...")
        proteins = fetch_fpbase_data()
        logger.info(f"Loaded {len(proteins)} proteins")

        # Save JSON if requested
        if args.save_json:
            with open(args.save_json, "w") as f:
                json.dump(proteins, f, indent=2)
            logger.info(f"Saved raw JSON data to {args.save_json}")

        # Generate and write TSV output
        if args.output:
            with open(args.output, "w", newline="") as f:
                write_tsv_output(proteins, f, args.limit, args.with_bright)
            logger.info(f"Generated TSV output to {args.output}")
        else:
            logger.debug("Writing TSV output to stdout")
            write_tsv_output(proteins, sys.stdout, args.limit, args.with_bright)

        # Generate and write FASTA output if requested
        if args.fasta:
            with open(args.fasta, "w") as f:
                write_fasta_output(proteins, f, args.limit)
            logger.info(f"Generated FASTA output to {args.fasta}")

    except Exception as e:
        logger.error(f"Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
