name: Conda test
defaults:
  run:
    shell: bash -l {0}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        exclude:
          - os: macos-latest
            python-version: "3.10"
          - os: macos-latest
            python-version: "3.12"
          - os: macos-latest
            python-version: "3.13"
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: setup miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        channels: conda-forge
        channel-priority: strict
        environment-file: environment.yml
        activate-environment: plannotate
        use-only-tar-bz2: true # Needed for osx-64 compatibility
        miniforge-variant: Miniforge3
        conda-solver: libmamba
        architecture: x86_64  # Force x86_64 architecture instead of arm64
        python-version: ${{ matrix.python-version }}

    - name: get conda info
      run: |
          conda info
          conda list
          which python
          python --version

    - name: install package
      run: |
        pip install .[test]

    - name: pytest unit
      run: |
        pytest --version
        pytest -n auto

    - name: get plannotate dbs
      run: |
        python -c "from plannotate.resources import download_databases; download_databases()"

    - name: pytest integration
      run: |
        pytest -n auto --run-integration
