name: Conda test

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: setup miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        environment-file: environment.yml
        activate-environment: plannotate

    - name: get conda info
      shell: bash -l {0}
      run: |
          conda info
          conda list

    - name: get plannotate dbs
      shell: bash -l {0}
      run: |
        python -c "from plannotate.resources import download_databases; download_databases()"

    - name: pytest
      shell: bash -l {0}    
      run: |
        pip install pytest
        pytest --version
        pytest
