name: Conda test

on:
  push:
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest]
        # python-version: ["3.10", "3.12", "3.14"]
        os: [ubuntu-latest]
        python-version: ["3.10"]
        # exclude:
        #   - os: macos-latest
        #     python-version: "3.10"
        #   - os: macos-latest
        #     python-version: "3.14"
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: setup miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        channels: conda-forge
        channel-priority: strict
        environment-file: environment.yml
        activate-environment: plannotate
        use-only-tar-bz2: true # Needed for osx-64 compatibility
        miniforge-variant: Miniforge3
        conda-solver: libmamba
        architecture: x86_64  # Force x86_64 architecture instead of arm64
        python-version: ${{ matrix.python-version }}

    - name: get conda info
      shell: bash -l {0}
      run: |
          conda info
          conda list

    - name: install package
      run: |
        ls -lhp
        pip install -e .

    - name: get plannotate dbs
      shell: bash -l {0}
      run: |
        python -c "from plannotate.resources import download_databases; download_databases()"

    - name: Install pytest
      shell: bash -l {0}
      run: |
        conda install pytest

    - name: pytest
      shell: bash -l {0}
      run: |
        pytest --version
        pytest
